### PR TITLE
Line spacing feature

### PR DESCRIPTION
**Pull request by manfredk**
Hi Omar,

finally, the line spacing feature revisited. Some remarks:

#### Options dialog:
linepress-with-line-spacing-options

The line-spacing box is simple. It includes just the line spacing in percent of line height and a checkbox to include comments (excluded by default). There is an intentional interaction between the settings for line spacing and line compression now - no spacing is applied for compressed lines.

#### Appearance with Line spacing 30% and Empty Line Compression 25%
linepress-with-line-spacing-options-code30

I've removed the debug entries from csproj, which probably were causing the appveyor build failing. Would you please check this?

Regards, 
Manfred

### CODE REVIEW

**Comment by omsharp** [comment]
Awesome. I'll start working on it.
I'll merge and then try to tackle the appveyor issue.

Thanks for PR, @manfredk

**Comment by omsharp** [comment]
PR is merged successfully. I still need to fix the appveyor issue.

**Comment by omsharp** [comment]
Issue with appveyor is solved, as follows:

1 - For some reason, the file "LinePress/Options/Infrastructure/StringExtensions.cs" on the branch "manfredk:line_spacing_feature" was added to the ignore list, not sure why really. Removed it from the ignore list and all is fine.

2 - Updated the Microsoft.VSSDK.BuildTools package, and that solved the "error MSB6006" issue.

I recommend that you merge the latest changes I've made, or refork it if you want. Just that in future we don't get the same issues again.

Thanks for the PR, @manfredk.

**Comment by omsharp** [comment]
By the way, I was wrong, editing the .csproj has nothing to do with the appveyor issue.
I just uncommented the entries and everything should be good.

**Comment by manfredk** [comment]
Hi Omar, good news, don't know how this ignoriert-List List came about. I
sync my fork with the New Master (or refork). Regards, Manfred

**Pull request merged**
